require 'lua'
require 'maths'
require 'lib'

require 'engine.love'
require 'lua.debug'
require 'engine.id'
require 'engine.color'
require 'engine.transform'
require 'engine.shader'
require 'engine.graphics2d'
require 'engine.shape'
require 'engine.mesh'
require 'engine.image'
require 'engine.font'
require 'engine.font_icons'
require 'engine.sound'
require 'engine.environment'

require 'engine.anchor'
require 'engine.mouse'
require 'engine.mouse_event'

require 'scene'

require 'engine.version'
require 'engine.event_manager'
require 'engine.animate'
require 'engine.sketch'
require 'engine.sketch_manager'
require 'engine.process_manager'
require 'engine.time_manager'
require 'engine.engine'
require 'engine.mobile'
